<?php

namespace DoctrineProxies\__CG__\Audubon\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \Audubon\Entities\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'id', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'first', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'last', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'phone', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'email', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'sightings'];
        }

        return ['__isInitialized__', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'id', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'first', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'last', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'phone', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'email', '' . "\0" . 'Audubon\\Entities\\Person' . "\0" . 'sightings'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setID($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setID', [$id]);

        return parent::setID($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirst', []);

        return parent::getFirst();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirst($first)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirst', [$first]);

        return parent::setFirst($first);
    }

    /**
     * {@inheritDoc}
     */
    public function getLast()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLast', []);

        return parent::getLast();
    }

    /**
     * {@inheritDoc}
     */
    public function setLast($last)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLast', [$last]);

        return parent::setLast($last);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getSightings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSightings', []);

        return parent::getSightings();
    }

    /**
     * {@inheritDoc}
     */
    public function setSightings($sightings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSightings', [$sightings]);

        return parent::setSightings($sightings);
    }

}
